import { Card, CardContent } from '@/components/ui/card';
import { AlertTriangle } from 'lucide-react';

export const metadata = {
  title: 'Disclaimer | QuickTextTool AI',
  description: 'Important disclaimers and limitations regarding the use of QuickTextTool AI writing tools and services.',
};

export default function Disclaimer() {
  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto px-4 py-16 max-w-4xl">
        <div className="flex items-center gap-3 mb-6">
          <AlertTriangle className="h-10 w-10 text-yellow-500" />
          <h1 className="text-4xl md:text-5xl font-bold bg-gradient-to-r from-blue-500 to-purple-600 bg-clip-text text-transparent">
            Disclaimer
          </h1>
        </div>
        <p className="text-muted-foreground mb-8">
          Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
        </p>

        <div className="space-y-6">
          <Card className="border-yellow-500/30">
            <CardContent className="pt-6 space-y-6">
              <section>
                <h2 className="text-2xl font-semibold mb-4">General Disclaimer</h2>
                <p className="text-muted-foreground leading-relaxed">
                  The information and tools provided by QuickTextTool AI are for general informational and assistance purposes only. While we strive to provide accurate and helpful AI-powered writing tools, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability of our services.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">AI-Generated Content Limitations</h2>
                <div className="space-y-4 text-muted-foreground">
                  <p className="leading-relaxed font-medium text-foreground">
                    IMPORTANT: All content generated by our AI tools should be reviewed and verified by the user.
                  </p>
                  <ul className="space-y-2 list-disc list-inside">
                    <li>AI outputs may contain factual errors, inaccuracies, or inconsistencies</li>
                    <li>Grammar corrections may not catch all errors or may introduce new ones</li>
                    <li>Paraphrasing may alter the intended meaning of text</li>
                    <li>Summaries may omit important details or context</li>
                    <li>Generated text may not be suitable for all purposes or contexts</li>
                    <li>AI cannot replace human judgment, expertise, or critical thinking</li>
                  </ul>
                </div>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">No Professional Advice</h2>
                <div className="bg-yellow-500/10 border border-yellow-500/30 p-4 rounded-lg">
                  <p className="text-muted-foreground leading-relaxed">
                    Our tools and any content generated through them do NOT constitute professional advice of any kind, including but not limited to:
                  </p>
                  <ul className="mt-3 space-y-2 text-muted-foreground list-disc list-inside">
                    <li>Legal advice or legal document preparation</li>
                    <li>Medical, health, or therapeutic advice</li>
                    <li>Financial, investment, or tax advice</li>
                    <li>Academic or educational certification</li>
                    <li>Professional writing or editing services</li>
                  </ul>
                  <p className="mt-3 text-muted-foreground leading-relaxed">
                    Always consult qualified professionals for matters requiring expert knowledge or legal compliance.
                  </p>
                </div>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">User Responsibility</h2>
                <div className="space-y-3 text-muted-foreground">
                  <p className="leading-relaxed">
                    By using our tools, you acknowledge and agree that:
                  </p>
                  <ul className="space-y-2 list-disc list-inside">
                    <li>You are solely responsible for verifying all AI-generated content</li>
                    <li>You must review and edit outputs before using them for any purpose</li>
                    <li>You are responsible for ensuring content meets your specific requirements</li>
                    <li>You will comply with applicable laws, regulations, and institutional policies</li>
                    <li>You will not rely solely on AI outputs for important decisions</li>
                    <li>Any actions you take based on AI-generated content are at your own risk</li>
                  </ul>
                </div>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">Academic Integrity</h2>
                <p className="text-muted-foreground leading-relaxed">
                  Students using our tools must comply with their institution's academic integrity policies. Our tools are designed to assist with learning and writing improvement, not to:
                </p>
                <ul className="mt-3 space-y-2 text-muted-foreground list-disc list-inside">
                  <li>Complete assignments on your behalf</li>
                  <li>Bypass academic requirements</li>
                  <li>Constitute original work or analysis</li>
                  <li>Replace your own thinking and effort</li>
                </ul>
                <p className="mt-3 text-muted-foreground leading-relaxed">
                  Check with your instructor or institution regarding acceptable use of AI writing tools.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">No Guarantee of Results</h2>
                <p className="text-muted-foreground leading-relaxed">
                  We do not guarantee that use of our tools will result in:
                </p>
                <ul className="mt-3 space-y-2 text-muted-foreground list-disc list-inside">
                  <li>Better grades or academic performance</li>
                  <li>Improved search engine rankings or SEO results</li>
                  <li>Increased engagement or conversions</li>
                  <li>Acceptance of applications, proposals, or submissions</li>
                  <li>Any specific outcome or benefit</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">Third-Party Services</h2>
                <p className="text-muted-foreground leading-relaxed">
                  Our tools use third-party AI services (Google Gemini API). We are not responsible for the accuracy, reliability, or availability of these third-party services. Any issues with the underlying AI models or their outputs are beyond our control.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">Service Availability</h2>
                <p className="text-muted-foreground leading-relaxed">
                  We make no guarantees about:
                </p>
                <ul className="mt-3 space-y-2 text-muted-foreground list-disc list-inside">
                  <li>Continuous, uninterrupted, or secure access to our services</li>
                  <li>Absence of errors, bugs, or technical issues</li>
                  <li>Availability during specific timeframes or peak usage</li>
                  <li>Compatibility with all devices, browsers, or systems</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">Limitation of Liability</h2>
                <div className="bg-red-500/10 border border-red-500/30 p-4 rounded-lg">
                  <p className="text-muted-foreground leading-relaxed font-medium">
                    TO THE FULLEST EXTENT PERMITTED BY LAW:
                  </p>
                  <p className="mt-2 text-muted-foreground leading-relaxed">
                    QuickTextTool AI and its operators shall not be liable for any direct, indirect, incidental, consequential, special, or punitive damages arising from or related to your use of our services, including but not limited to:
                  </p>
                  <ul className="mt-3 space-y-2 text-muted-foreground list-disc list-inside">
                    <li>Loss of data, grades, opportunities, or income</li>
                    <li>Academic or professional consequences</li>
                    <li>Reliance on AI-generated content</li>
                    <li>Service interruptions or errors</li>
                    <li>Any other damages or losses</li>
                  </ul>
                </div>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">Updates to This Disclaimer</h2>
                <p className="text-muted-foreground leading-relaxed">
                  We reserve the right to update this disclaimer at any time. Changes will be posted on this page with an updated date.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-semibold mb-4">Contact</h2>
                <p className="text-muted-foreground leading-relaxed">
                  If you have questions about this disclaimer, please <a href="/contact" className="text-primary hover:underline">contact us</a>.
                </p>
              </section>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
